const pagesData = {
    canConfigure: {
        name: 'canConfigure',
        value: 'canconfigure',
        text: ' конфигурацию',
        classChecked: 'far fa-check-square',
        classUnchecked: 'far fa-square',
        tooltip: '',
    },
    canChangeUsers: {
        name: 'canChangeUsers',
        value: 'canchangeusers',
        text: ' пользователей',
        classChecked: 'far fa-check-square',
        classUnchecked: 'far fa-square',
        tooltip: '',
    },
    canChangeMenu: {
        name: 'canChangeMenu',
        value: 'canchangemenu',
        text: ' меню',
        classChecked: 'far fa-check-square',
        classUnchecked: 'far fa-square',
        tooltip: '',
    },
    canChangeMaterials: {
        name: 'canChangeMaterials',
        value: 'canchangematerials',
        text: ' материалы',
        classChecked: 'far fa-check-square',
        classUnchecked: 'far fa-square',
        tooltip: '',
    },
    enabled: {
        name: 'enabled',
        value: 'enabled',
        text: ' Активен',
        classChecked: 'far fa-check-square',
        classUnchecked: 'far fa-square',
        tooltip: '',
    },
    deleteUser: {
        name: 'deleteUser',
        value: null,
        text: '',
        classChecked: 'fas fa-user-slash',
        classUnchecked: 'fas fa-user-slash',
        tooltip: 'Удалить пользователя',
    },
    addUser: {
        name: 'addUser',
        value: null,
        text: '',
        classChecked: 'fas fa-user-plus fa-2x',
        classUnchecked: 'fas fa-user-plus fa-2x',
        tooltip: 'Добавить пользователя',
    },
    changePassword: {
        name: 'changePassword',
        value: null,
        text: '',
        classChecked: 'fas fa-key',
        classUnchecked: 'fas fa-key',
        tooltip: 'Сменить пароль',
    },
    apply: {
        name: 'apply',
        value: null,
        text: '',
        classChecked: 'far fa-check-circle fa-2x',
        classUnchecked: 'far fa-check-circle fa-2x',
        tooltip: 'Записать изменения',
    },
    revert: {
        name: 'revert',
        value: null,
        text: '',
        classChecked: 'fa fa-undo fa-2x',
        classUnchecked: 'fa fa-undo fa-2x',
        tooltip: 'Отменить изменения',
    },
    userName: {
        name: 'userName',
        value: 'username',
        text: 'i.petrov',
        classChecked: '',
        classUnchecked: '',
        tooltip: '',
        validation: 'Неверное имя пользователя',
    },
    firstName: {
        name: 'firstName',
        value: 'firstname',
        text: 'Иван',
        classChecked: '',
        classUnchecked: '',
        tooltip: '',
    },
    lastName: {
        name: 'lastName',
        value: 'lastname',
        text: 'Петров',
        classChecked: '',
        classUnchecked: '',
        tooltip: '',
    },
    email: {
        name: 'email',
        value: 'email',
        text: 'i.petrov@mail.ru',
        classChecked: '',
        classUnchecked: '',
        tooltip: '',
    },
    description: {
        name: 'description',
        value: 'description',
        text: '',
        classChecked: '',
        classUnchecked: '',
        tooltip: '',
    },
};

export default pagesData;
